import { SessionProvider } from "next-auth/react"
import 'bootstrap/dist/css/bootstrap.min.css'
import Nav from '../components/Navbar'
import Head from "next/head";

function MyApp({ Component, pageProps:{ session, ...pageProps }, }) {
  return(
    <>
    <SessionProvider session={session}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=.6" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>  
      <Nav />
      
     
          <Component {...pageProps} />
          
      </SessionProvider>
    </>
  )
   
}

export default MyApp
