import 'bootstrap/dist/css/bootstrap.min.css'
import Nav from '../components/Navbar'
import Head from "next/head";
function MyApp({ Component, pageProps }) {
  return(
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=.6" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav/>
      <Component {...pageProps} />
    </>
  )
   
}

export default MyApp
