import Head from "next/head";
import Link from "next/link";
import React, { useState } from 'react';

import conectarDB from "../lib/dbConnect";
//import Movie from "../models/Movie";
import Oveja from "../models/Oveja";

export default function Home({ movies }) {
  console.log(movies);
  const [count, setCount] = useState(0);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container">
      <div className="card">
        <div className="card-header">
        <h1 className="text-center" >Comunidad del Rey</h1>
        </div>
        <div className="card-body">
        
        <Link href="/new">
          <a className="btn btn-primary w-100 mb-2">Agregar</a>
        </Link>
        <table className="table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre y Apellido</th>
                <th scope="col">Cedula</th>
                <th scope="col">Telefono</th>
                <th scope="col">...</th>
              </tr>
            </thead>
            <tbody>
              
            {movies.map(({ _id, nombre, apellido,cedula,tel2,tel1 }) => (
              <tr key={_id}>
              <th scope="row" ></th>
                <td>{nombre} - {apellido} </td>
                <td>{cedula}</td>
                <td>{tel2}</td>
                <td>
                <Link href={`/${_id}`}>
                <a className="btn btn-success btn-sm">Más info...</a>
              </Link>
                </td>
              </tr>
                
              ))
                
              }
            </tbody>
          </table>
        
       
          
        </div>
        <div className="card-footer text-muted">
          2 days ago
        </div>
      </div>

      </main>
    </div>
  );
}

export async function getServerSideProps() {
  try {
    await conectarDB();

    const res = await Oveja.find({});

    const movies = res.map((doc) => {
      const movie = doc.toObject();
      movie.nacio=`${movie.nacio};`
      movie._id = `${movie._id}`;
      return movie;
    });

    // console.log(res)

    return { props: { movies } };
  } catch (error) {
    console.log(error);
  }
}
