import Head from "next/head";
import Link from "next/link";
import useSWR from "swr";
import { useRouter } from "next/dist/client/router";

const fetcher = async (url) => {
  const res = await fetch(url);
  console.log(url)
  // If the status code is not in the range 200-299,
  // we still try to parse and throw it.
  if (!res.ok) {
    const error = new Error("An error occurred while fetching the data.");
    // Attach extra info to the error object.
    error.info = await res.json();
    error.status = res.status;
    throw error;
  }

  const { data } = await res.json();
  return data;
};

const EditMovie = () => {
  const router = useRouter();
  const { id } = router.query;
    console.log(id)
  const { data: movie, error } = useSWR(
    id ? `/api/oveja/ruto/${id}` : null,
    fetcher
  );

  if (error) {
    return <div>Error Encontrado</div>;
  }

  if (!movie) {
    return (
      <div className="container mt-5 text-center">
        <h1>Loading...</h1>
      </div>
    );
  }

  

  return (
    <div className="container">
      <h2 className="text-center">Datos Filtrados</h2>
          <div>
      <Head>
        <title>Create Next App</title>
        <meta name="viewport" content="width=device-width, initial-scale=.5" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container" >
      <div className="card">
        <div className="card-header">
        <h1 className="text-center" >Comunidad del Rey</h1>
        </div>
        <div className="card-body">
        
        <Link href="/new">
          <a className="btn btn-primary w-100 mb-2">Agregar</a>
        </Link>
        <div className="table-responsive">
        <table className="table table-responsive">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Nombre y Apellido</th>
                <th scope="col">Cedula</th>
                <th scope="col">Telefono</th>
                <th scope="col">...</th>
              </tr>
            </thead>
            <tbody >
              
            {movie.map(({ _id, nombre, apellido,cedula,tel2,tel1 }) => (
              <tr key={_id}>
              <th scope="row" ></th>
                <td>{nombre} - {apellido} </td>
                <td><strong>{cedula} </strong></td>
                <td>{tel2}</td>
                <td>
                <Link href={`../${_id}`}>
                <a className="btn btn-success btn-xs">Más info...</a>
              </Link>
                </td>
              </tr>
                
              ))
                
              }
            </tbody>
          </table>
       </div>
        
       
          
        </div>
        
      </div>

      </main>
    </div>
    </div>
  );
};

export default EditMovie;
